spring:
  h2.console:
    enabled: true
    path: /console
  datasource:
    url: jdbc:h2:file:./todo-db
    username: mat
    password: password
    driverClassName: org.h2.Driver
  jpa.hibernate.ddl-auto: create-drop
task.template.allowMultipleTasks: false
